Update azure-pipelines-1.yml for Azure Pipelines

diff --git a/azure-pipelines-1.yml b/azure-pipelines-1.yml
--- a/azure-pipelines-1.yml
+++ b/azure-pipelines-1.yml
@@ -13,3 +13,13 @@ stages:
     - script: |
         echo "Hello from Job A"
         exit 1   # deliberately failing, but pipeline will continue due to continueOnError: true
+
+  - job: jobnameB
+    timeoutInMinutes: 5
+    continueOnError: true
+    displayName: "this is B single job demo"
+    cancelTimeoutInMinutes: 2
+    steps:
+    - script: |
+        echo "Hello from Job B"
+        exit 1   # deliberately failing, but pipeline will continue due to continueOnError: true
